/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RecoveryGuideRouteImport } from './routes/recovery-guide'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OperatorOsRouteImport } from './routes/operator-os'
import { Route as ForRealEstateRouteImport } from './routes/for-real-estate'
import { Route as ForPropertyManagementRouteImport } from './routes/for-property-management'
import { Route as ForHvacRouteImport } from './routes/for-hvac'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryGuideRoute = RecoveryGuideRouteImport.update({
  id: '/recovery-guide',
  path: '/recovery-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorOsRoute = OperatorOsRouteImport.update({
  id: '/operator-os',
  path: '/operator-os',
  getParentRoute: () => rootRouteImport,
} as any)
const ForRealEstateRoute = ForRealEstateRouteImport.update({
  id: '/for-real-estate',
  path: '/for-real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPropertyManagementRoute = ForPropertyManagementRouteImport.update({
  id: '/for-property-management',
  path: '/for-property-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ForHvacRoute = ForHvacRouteImport.update({
  id: '/for-hvac',
  path: '/for-hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/audit': typeof AuditRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-hvac': typeof ForHvacRoute
  '/for-property-management': typeof ForPropertyManagementRoute
  '/for-real-estate': typeof ForRealEstateRoute
  '/operator-os': typeof OperatorOsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recovery-guide': typeof RecoveryGuideRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/audit': typeof AuditRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-hvac': typeof ForHvacRoute
  '/for-property-management': typeof ForPropertyManagementRoute
  '/for-real-estate': typeof ForRealEstateRoute
  '/operator-os': typeof OperatorOsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recovery-guide': typeof RecoveryGuideRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/audit': typeof AuditRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-hvac': typeof ForHvacRoute
  '/for-property-management': typeof ForPropertyManagementRoute
  '/for-real-estate': typeof ForRealEstateRoute
  '/operator-os': typeof OperatorOsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recovery-guide': typeof RecoveryGuideRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessment'
    | '/audit'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/for-hvac'
    | '/for-property-management'
    | '/for-real-estate'
    | '/operator-os'
    | '/pricing'
    | '/privacy'
    | '/recovery-guide'
    | '/services'
    | '/terms'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/audit'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/for-hvac'
    | '/for-property-management'
    | '/for-real-estate'
    | '/operator-os'
    | '/pricing'
    | '/privacy'
    | '/recovery-guide'
    | '/services'
    | '/terms'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assessment'
    | '/audit'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/for-hvac'
    | '/for-property-management'
    | '/for-real-estate'
    | '/operator-os'
    | '/pricing'
    | '/privacy'
    | '/recovery-guide'
    | '/services'
    | '/terms'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  AuditRoute: typeof AuditRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForHvacRoute: typeof ForHvacRoute
  ForPropertyManagementRoute: typeof ForPropertyManagementRoute
  ForRealEstateRoute: typeof ForRealEstateRoute
  OperatorOsRoute: typeof OperatorOsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecoveryGuideRoute: typeof RecoveryGuideRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-guide': {
      id: '/recovery-guide'
      path: '/recovery-guide'
      fullPath: '/recovery-guide'
      preLoaderRoute: typeof RecoveryGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator-os': {
      id: '/operator-os'
      path: '/operator-os'
      fullPath: '/operator-os'
      preLoaderRoute: typeof OperatorOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-real-estate': {
      id: '/for-real-estate'
      path: '/for-real-estate'
      fullPath: '/for-real-estate'
      preLoaderRoute: typeof ForRealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-property-management': {
      id: '/for-property-management'
      path: '/for-property-management'
      fullPath: '/for-property-management'
      preLoaderRoute: typeof ForPropertyManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-hvac': {
      id: '/for-hvac'
      path: '/for-hvac'
      fullPath: '/for-hvac'
      preLoaderRoute: typeof ForHvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  AuditRoute: AuditRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForHvacRoute: ForHvacRoute,
  ForPropertyManagementRoute: ForPropertyManagementRoute,
  ForRealEstateRoute: ForRealEstateRoute,
  OperatorOsRoute: OperatorOsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecoveryGuideRoute: RecoveryGuideRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
